# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-22 11:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=120)),
                ('description', models.TextField(default='')),
                ('shortdescription', models.TextField(default='')),
                ('price', models.FloatField()),
                ('discount', models.FloatField()),
                ('stock_status', models.CharField(max_length=64)),
                ('sku', models.CharField(max_length=64)),
            ],
        ),
    ]
