# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-24 06:09
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Brands',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=120)),
                ('slug', models.CharField(max_length=120, unique=True)),
                ('description', models.TextField(default='')),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=150)),
                ('slug', models.CharField(max_length=150, unique=True)),
                ('description', models.TextField(default='')),
            ],
        ),
        migrations.CreateModel(
            name='MenuModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('description', models.TextField(default='')),
                ('type', models.CharField(choices=[('url', 'URL'), ('category', 'Category'), ('tag', 'Tag'), ('product', 'Product'), ('brand', 'Brand')], max_length=64)),
                ('content', models.TextField(default='')),
                ('serial_no', models.IntegerField(default=0)),
                ('disabled', models.BooleanField()),
                ('parent', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ecom_app.MenuModel')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('description', models.TextField()),
                ('short_description', models.TextField()),
                ('price', models.IntegerField(default=0)),
                ('discount', models.FloatField(default=0)),
                ('stock_status', models.CharField(max_length=1, null=True)),
                ('image_file_path', models.CharField(default='', max_length=300)),
                ('create_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('update_date', models.DateTimeField(auto_now=True, null=True)),
                ('brand', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ecom_app.Brands')),
                ('category', models.ManyToManyField(to='ecom_app.Category')),
            ],
        ),
        migrations.CreateModel(
            name='ProductReview',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('email', models.EmailField(max_length=250)),
                ('review', models.CharField(max_length=300)),
                ('status', models.BooleanField()),
                ('create_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('update_date', models.DateTimeField(auto_now=True, null=True)),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ecom_app.Product')),
            ],
        ),
        migrations.CreateModel(
            name='SiteSetting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=100)),
                ('logo_file_path', models.CharField(default='', max_length=300)),
                ('meta_title', models.CharField(default='', max_length=200)),
                ('meta_description', models.TextField(default='')),
                ('meta_keyword', models.CharField(max_length=200)),
                ('short_desc', models.TextField(default='')),
                ('long_desc', models.TextField(default='')),
                ('phone', models.CharField(default='', max_length=15)),
                ('email', models.CharField(default='', max_length=100)),
                ('contact_details', models.TextField(default='')),
                ('facebook_url', models.CharField(default='', max_length=300)),
                ('twitter_url', models.CharField(default='', max_length=300)),
                ('google_plus_url', models.CharField(default='', max_length=300)),
                ('youtube_url', models.CharField(default='', max_length=300)),
                ('copyrights', models.CharField(max_length=200)),
                ('create_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('update_date', models.DateTimeField(auto_now=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Tags',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=150)),
                ('slug', models.CharField(max_length=150, unique=True)),
                ('description', models.TextField(default='')),
            ],
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mobile', models.CharField(default='', max_length=15)),
                ('position', models.CharField(default='USER', max_length=24)),
                ('reset_password_token', models.CharField(default=None, max_length=128, null=True, unique=True)),
                ('is_reset_req_flag', models.BooleanField()),
                ('reg_complete_token', models.CharField(default=None, max_length=128, null=True, unique=True)),
                ('dj_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='tags',
            field=models.ManyToManyField(to='ecom_app.Tags'),
        ),
    ]
