# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-22 15:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ecom_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductReview',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('email', models.EmailField(max_length=250)),
                ('review', models.CharField(max_length=300)),
                ('status', models.BooleanField()),
                ('create_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('update_date', models.DateTimeField(auto_now=True, null=True)),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ecom_app.Product')),
            ],
        ),
        migrations.AddField(
            model_name='users',
            name='reg_complete_token',
            field=models.CharField(default=None, max_length=128, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='users',
            name='reset_password_token',
            field=models.CharField(default=None, max_length=128, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='users',
            name='position',
            field=models.CharField(default='user', max_length=24),
        ),
    ]
