# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-22 12:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecom_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='imageurl',
            field=models.CharField(default='', max_length=32),
        ),
    ]
