# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-23 02:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecom_app', '0002_auto_20171122_2119'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='position',
            field=models.CharField(default='USER', max_length=24),
        ),
    ]
