# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-11-07 15:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecom_app', '0002_auto_20171107_2126'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='mobile',
            field=models.CharField(default='', max_length=15),
        ),
    ]
