# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-24 16:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecom_app', '0002_auto_20170824_2224'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tags',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=150)),
                ('slug', models.CharField(max_length=150, unique=True)),
                ('description', models.TextField(default='')),
            ],
        ),
    ]
