# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-19 14:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ecom_app', '0002_menu'),
    ]

    operations = [
        migrations.CreateModel(
            name='MenuModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('description', models.TextField(default='')),
                ('type', models.CharField(choices=[('url', 'URL'), ('category', 'Category'), ('tag', 'Tag'), ('product', 'Product'), ('brand', 'Brand')], max_length=64)),
                ('content', models.TextField(default='')),
                ('serial_no', models.IntegerField(default=0)),
                ('disabled', models.BooleanField()),
                ('parent', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ecom_app.MenuModel')),
            ],
        ),
        migrations.RemoveField(
            model_name='menu',
            name='parent',
        ),
        migrations.DeleteModel(
            name='Menu',
        ),
    ]
