# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-22 12:12
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecom_app', '0003_auto_20170822_1811'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='created',
            new_name='created_at',
        ),
    ]
