# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-18 14:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecom_app', '0003_auto_20171107_2127'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='position',
            field=models.CharField(choices=[('teacher', 'teacher'), ('ceo', 'ceo')], default='ceo', max_length=24),
        ),
    ]
