# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-14 14:19
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecom_app', '0003_auto_20170919_2027'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='imageurl',
            new_name='image_file_path',
        ),
    ]
