# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-01 18:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecom_app', '0003_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='imageurl',
            field=models.CharField(default='', max_length=300),
        ),
    ]
