# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-22 12:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecom_app', '0004_auto_20170822_1812'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=150)),
                ('slug', models.CharField(max_length=150, unique=True)),
                ('description', models.TextField(default='')),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.ManyToManyField(to='ecom_app.Category'),
        ),
    ]
