# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-10-17 09:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecom_app', '0004_auto_20171014_2019'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSetting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('logo_file_path', models.CharField(default='', max_length=300)),
                ('meta_title', models.CharField(max_length=200)),
                ('meta_description', models.TextField()),
                ('meta_keyword', models.CharField(max_length=200)),
                ('short_desc', models.TextField()),
                ('long_desc', models.TextField()),
                ('copyrights', models.CharField(max_length=200)),
                ('create_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('update_date', models.DateTimeField(auto_now=True, null=True)),
            ],
        ),
    ]
