# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-11 21:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ecom_app', '0005_auto_20170822_1834'),
    ]

    operations = [
        migrations.CreateModel(
            name='Brands',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=120)),
                ('slug', models.CharField(max_length=120, unique=True)),
                ('description', models.TextField(default='')),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='brands',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ecom_app.Brands'),
        ),
    ]
