# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-05 15:04
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecom_app', '0005_auto_20170902_0059'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='categories',
            new_name='category',
        ),
    ]
