# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-21 06:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecom_app', '0005_sitesetting'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesetting',
            name='contact_details',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='email',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='facebook_url',
            field=models.CharField(default='', max_length=300),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='phone',
            field=models.CharField(default='', max_length=15),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='twitter_url',
            field=models.CharField(default='', max_length=300),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='youtube_url',
            field=models.CharField(default='', max_length=300),
        ),
        migrations.AlterField(
            model_name='sitesetting',
            name='long_desc',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='sitesetting',
            name='meta_description',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='sitesetting',
            name='meta_title',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='sitesetting',
            name='short_desc',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='sitesetting',
            name='title',
            field=models.CharField(default='', max_length=100),
        ),
    ]
