# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-05 19:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecom_app', '0006_auto_20170905_2104'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='tags',
        ),
        migrations.AddField(
            model_name='product',
            name='tags',
            field=models.ManyToManyField(to='ecom_app.Tags'),
        ),
    ]
