# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-21 07:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecom_app', '0006_auto_20171021_1225'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesetting',
            name='google_plus_url',
            field=models.CharField(default='', max_length=300),
        ),
    ]
