# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-21 09:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecom_app', '0007_sitesetting_google_plus_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=120, unique=True)),
                ('email', models.CharField(max_length=120, unique=True)),
                ('password', models.CharField(max_length=12, null=True)),
            ],
        ),
    ]
