# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-10-25 08:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecom_app', '0009_product_stock_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='stock_status',
            field=models.ImageField(default=1, upload_to=''),
        ),
    ]
