# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-10-25 08:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecom_app', '0010_auto_20171025_1444'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='stock_status',
            field=models.IntegerField(),
        ),
    ]
