# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-11-01 05:49
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecom_app', '0014_auto_20171026_0933'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Suppliers',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='brands',
            new_name='brand',
        ),
    ]
